# Generated by Django 3.1.7 on 2021-02-24 23:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210224_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000)])),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('lsat_try_datetime', models.DateTimeField(auto_now=True)),
                ('internal_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.basket')),
            ],
        ),
    ]
