# Generated by Django 3.1.7 on 2021-02-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='lsat_try_datetime',
            new_name='last_try_datetime',
        ),
        migrations.AddField(
            model_name='invoice',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='cid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='refnumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('0', 'Created'), ('1', 'In Payment'), ('2', 'Payed'), ('3', 'Rejected')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tracing_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
