# Generated by Django 3.1.7 on 2021-02-25 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210224_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='book',
        ),
        migrations.RemoveField(
            model_name='basket',
            name='count',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='basket',
        ),
        migrations.AlterField(
            model_name='basket',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='baskets', to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.basket')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.book')),
            ],
            options={
                'unique_together': {('book', 'basket')},
            },
        ),
    ]
