# Generated by Django 3.1.7 on 2021-02-25 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_basket_create_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.invoice'),
        ),
    ]
