# Generated by Django 3.1.7 on 2021-02-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_basket_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Done')], default='0', max_length=1),
        ),
    ]
