# Generated by Django 3.1.7 on 2021-02-26 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210226_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='last_try_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
