# Generated by Django 3.1.7 on 2021-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210226_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delivery_phone_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='land_line',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
