# Generated by Django 3.1.7 on 2021-02-27 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210227_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basket',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid phone number', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
    ]
