# Generated by Django 3.1.7 on 2021-02-27 15:21

import core.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210227_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfilePhoneVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=core.helpers.generate_code, max_length=13)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('query_times', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
                ('burnt', models.BooleanField(default=False)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='core.userprofile')),
            ],
        ),
    ]
