# Generated by Django 3.1.7 on 2021-03-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210228_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_return_url', models.URLField(blank=True, null=True)),
                ('delivery_fee', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
