# Generated by Django 3.1.7 on 2021-03-01 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000)]),
            preserve_default=False,
        ),
    ]
