# Generated by Django 3.1.7 on 2021-03-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_invoice_delivery_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='payment_return_url',
        ),
    ]
