# Generated by Django 3.1.7 on 2021-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_config_payment_return_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='related_books',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='core.Book'),
        ),
    ]
