# Generated by Django 3.1.7 on 2021-03-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_book_related_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='no_delivery_fee',
            field=models.BooleanField(default=False),
        ),
    ]
