# Generated by Django 3.1.7 on 2021-03-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_basket_no_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authored_books', to='core.Person'),
        ),
    ]
