# Generated by Django 3.1.7 on 2021-04-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210405_1008'),
        ('core', '0028_auto_20210307_1437'),
    ]

    operations = [
    ]
